services:
  - type: web
    name: evolution-insurance-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run insurance_dashboard.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1 